<?php
$_silverHelper = Mage::helper('silverframework/silver');
$_enable = $_silverHelper->settings['settings']['left_callout_enable'];
$_html = $_silverHelper->settings['settings']['left_callout_html'];
?>

<?php if($_enable): ?>
	<?php if($_html == ''): ?>
		<?php echo $this->getLayout()->createBlock('core/template')->setTemplate('silverframework/callouts/left.phtml')->toHtml(); ?>
	<?php else: ?>
		<?php echo $_html; ?>
	<?php endif; ?>
<?php endif; ?>
