<div class="menu-left-container"> 
  <div class="menu-left-content clearfix">
	<div class="menu-left-nav">
		<ul class="menu-left">
		<?php foreach ($this->getStoreCategories() as $_category): ?>
		 <?php echo $this->drawItem($_category) ?>
		<?php endforeach ?>
		</ul>
		<?php echo $this->getChildHtml('topLeftLinks') ?>
	</div>
   </div>
</div>  
<!--<script type="text/javascript">
	Event.observe(window, 'load', function() {
		var LIs = $$('.menu-left')[0].childElements();
		//alert('abc');
		for(var i =0;i<LIs.length;i++){
			var children = LIs[i].childElements();
			if(children.length>=2){
				if(LIs[i].hasClassName('active')){
					children[1].show();
				}else{
					children[1].hide();
				}
			}
		}
	}); 
</script>-->