<script src="<?php echo $this->getSkinUrl().'js/jquery.js'; ?>" type="text/javascript"></script>
<script src="<?php echo $this->getSkinUrl().'js/easySlider1.5.js' ?>" type="text/javascript"></script>
<script src="<?php echo $this->getSkinUrl().'js/play.js' ?>" type="text/javascript"></script>
<?php $products = $this->getFeaturedProduct(); ?>
<?php if($products): ?>
<div id="container">
	<div id="content">
		<div id="slider">
			<ul>
				<?php foreach($products as $product): ?>
				<li>
					<div class="cms-index-index index-pro-infor">
						<h1><?php echo $this->getManufacturerName($product->getId())->getName(); ?></h1>
						<h2 class="product-name">
							<a href="<?php echo $product->getProductUrl() ?>"><?php echo $this->htmlEscape(Mage::getModel('catalog/product')->load($product->getId())->getName()) ?></a>
						</h2>
					</div>
					<?php echo $this->getPriceHtml(Mage::getModel('catalog/product')->load($product->getId()), true) ?>
					<a href="<?php echo $product->getProductUrl() ?>">
						<img src="<?php echo $this->helper('catalog/image')->init(Mage::getModel('catalog/product')->load($product->getId()), 'small_image')->resize(180); ?>" alt="<?php echo $this->htmlEscape(Mage::getModel('catalog/product')->load($product->getId())->getName()) ?>" title="<?php echo $this->htmlEscape(Mage::getModel('catalog/product')->load($product->getId())->getName()) ?>" />
					</a>
				</li>
				<?php endforeach; ?>
			</ul>
		</div>
	</div>
</div>
<?php endif; ?>
